# **Lab 5: Numpy Exercises**

In [1]:
import numpy as np

#  1. insert the correct code for creating a numpy array

a = np.array([1, 2, 3, 4, 5]) # use np
print(a) # [1 2 3 4 5]

[1 2 3 4 5]


In [2]:
#  2. consider this function:

def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a

#     what is the difference between what(1), what(2) and what(3)

print(what(1)) # what do these print and why?
print(what(2))
print(what(3))

1
[1 2 3 4]
2
[[1 2 3 4]]
3
[[[1 2 3 4]]]


In [3]:
#  3. insert the correct argument for creating a numpy array with 2 dimensions

a = np.array([1, 2, 3, 4], ndmin = 2)
print(a) # should print [[1 2 3 4]]

[[1 2 3 4]]


In [4]:
#  4. insert the correct syntax for checking the number of dimensions of a numpy array

a = np.array([1, 2, 3, 4])
print(a.ndim) # should print 1 (must refer to a)

b = np.array([[1, 2], [3, 4]])
print(b.ndim) # should print 2 (must refer to b)

1
2


In [5]:
#  5. insert the correct syntax for printing the first item in the array:

a = np.array([1, 2, 3, 4])
print(a[0]) # should print 1 must use a

1


In [6]:
#  6. insert the correct syntax for printing the number 50 from the array

a = np.array([10, 20, 30, 40, 50])
print(a[4]) # should print 50 must use a

50


In [7]:
#  7. insert the correct syntax for printing the number 50 from the array

a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a[1,0]) # should print 50 must use a

50


In [8]:
#  8. use negative indexing to print the last item in the array

a = np.array([10, 20, 30, 40, 50])
print(a[-1]) # should print 50 must use a

50


In [10]:
#  9. slice out everything from the second item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4]) # should print [15 20 25] must use a

[15 20 25]


In [11]:
# 10.slice out everything from the third item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[2:4]) # should print [20 25] must use a

[20 25]


In [12]:
# 11. slice out every other item from the second item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4:2]) # should print [15 25] must use a

[15 25]


In [15]:
# 12. slice out every other item from the entire array

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[0::2]) # should print [10 20 30 40] must use a

[10 20 30 40]


In [17]:
# 13. insert correct syntax to print the datatype of an array

a = np.array([1, 2, 3])
print(a.dtype) # should print something indicating this is an array of integers

int64


In [18]:
# 14. insert the correct argument to specify that array should be of type STRING

a = np.array([1, 2, 3, 4], dtype="S")

#     then predict and explain the output for the following expressions

print(a.dtype)
print(a[0] + a[1])
a = np.array([5, 1, -1, 3], dtype='S')
b = a.astype('i') # what happens here?
print(b[0] + b[1] + b[3])
print(a[0] + a[1] + a[3])

|S1
b'12'
9
b'513'


In [19]:
# 15. insert correct method to change data type to integer

a = np.array([1.1, 2.1, 3.1])
b = a.astype("i")
print(b) # should print [1 2 3] now

[1 2 3]


In [20]:
# 16. use the correct method to make a copy of the array

a = np.array([1, 2, 3, 4, 5])
x = a.copy() # must use a to make a copy of it

#     then predict the effect of the following expressions

x[0] = -5
print(a) # does a see the change?
b = a
b[0] = -25
print(a) # does a see the change?

[1 2 3 4 5]
[-25   2   3   4   5]


In [21]:
# 17. use the correct method to make a view of this array:

a = np.array([1, 2, 3, 4, 5])
d = a.view()

#     then predict the effect of these expressions:

print(a.base)
print(d.base) # why is this different from all the others?
b = a
print(b.base)
c = a.copy()
print(c.base)

None
[1 2 3 4 5]
None
None


In [26]:
# 18.predict (and explain) the outcome of these expressions

a = np.array([1, 2, 3, 4])
print(a.shape)
a.reshape(1, 4)

a.reshape(2, 2)

a.reshape(4, 1)


(4,)


array([[1],
       [2],
       [3],
       [4]])

In [25]:
# 19. use the correct numpy method to change the shape of an array from 1-D to 2-D:

a = np.array([1, 2, 3, 4])
a= a.reshape(2,2) # write code here must use a
print(a) # must print [[1, 2] [3 4]]

#     now predict and explain the output of these expressions

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)
b = a.reshape(3, 4)
print(b)

[[1 2]
 [3 4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# 20. use correct numpy method to change shape of an array from 2-D to 1-D

a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape(12) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
# 21. use a correct numpy method to join two arrays into a single array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b)) # use np, a and b somehow
print(c) # must print [1 2 3 4 5 6]

#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter?
print(c) # what gets printed and why?
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)?
print(c) # what gets printed and why?

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# 22. use correct numpy syntax to find all items with value 4

a = np.array([1, 2, 3, 4, 5, 4, 4])
where = np.where(a == 4) # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

(array([3, 5, 6]),)


In [30]:
# 23. use the correct numpy method to return a sorted array

a = np.array([3, 2, 0, 1])
b = np.sort(a) # complete statement, must use np and a
print(b) # must print [0 1 2 3]

[0 1 2 3]


In [35]:
# 24. solve exercise 3-1 on page 57

# write your solution here
## Dependencies
import numpy as np
## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]
names = ['alice', 'bob', 'tim']
salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
[0.4, 0.5, 0.5],
[0.1, 0.2, 0.1]])
## One-liner
max_income = np.max(salaries - salaries * taxation)

#for lab
after_tax_income = (salaries - salaries * taxation).max(axis=1)

max_index = np.argmax(after_tax_income)
max_name = names[max_index]

## Result
print(max_income)

print("The person with the max income was: ", max_name)

81.0
The person with the max income was:  tim


In [38]:

# 25. predict and explain the effect of the following expressions

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.average(a, axis=0)) # review the meaning of the axis parameter
print(np.average(a, axis=1))
print(np.average(a, axis=2))

print(a)


[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# 26. predict and explain the effect of the following expressions

a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

b = np.sort(a, axis=0)
print(b) # what gets printed and why?
c = np.sort(a, axis=1)
print(c)
d = np.sort(a, axis=2)
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 10]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 7  5  6]
  [22  8  9]]

 [[ 4 12 10]
  [11 14 15]
  [16 17 18]]

 [[13 20 21]
  [19 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 5  6 22]
  [ 7  8  9]]

 [[10 11 12]
  [ 4 14 15]
  [16 17 18]]

 [[19 20 21]
  [13 23 24]
  [25 26 27]]]
